import { useState } from 'react'
import { X, Download, Copy, Save } from 'lucide-react'
import { savePostmortem } from '../utils/api.js'

function generateContent(analysis) {
  const now = new Date().toLocaleString()
  const cascade = (analysis.cascadeChain || analysis.cascade_chain || []).join(' → ')
  const services = (analysis.affectedServices || analysis.affected_services || [])
    .map(s => `- **${s.name}** — ${s.status}${s.role ? ` (${s.role})` : ''}`)
    .join('\n')
  const timeline = (analysis.timeline || [])
    .map(e => `- \`${e.time || ''}\` ${e.event || e.description || ''} ${e.service ? `[${e.service}]` : ''}`)
    .join('\n')

  return `# Incident Postmortem
*Generated: ${now}*

## Severity
**${(analysis.severity || 'Unknown').toUpperCase()}** — Confidence: ${analysis.confidenceScore || analysis.confidence_score || 0}%

## Root Cause
${analysis.rootCause || analysis.root_cause || 'Unknown'}

**Primary service:** ${analysis.rootCauseService || analysis.root_cause_service || 'Unknown'}

## Business Impact
${analysis.businessImpact || analysis.business_impact || 'Not assessed'}

## Affected Services
${services || 'None identified'}

## Failure Cascade
${cascade || 'N/A'}

## Timeline
${timeline || 'No timeline available'}

## Immediate Remediation
${analysis.immediateFix || analysis.immediate_fix || 'See engineering team'}

## Long-Term Prevention
${analysis.permanentFix || analysis.permanent_fix || 'See engineering team'}

## Alternatives Considered
${(analysis.alternatives || []).map(a => `- ${a.cause} (${a.confidence}% confidence)`).join('\n') || 'None'}

---
*Generated by CauseAI*`
}

export function PostmortemModal({ analysis, onClose }) {
  const content = generateContent(analysis)
  const title = `Incident: ${analysis.rootCauseService || analysis.root_cause_service || 'Unknown'} — ${analysis.severity || 'Unknown'}`
  const [saved, setSaved] = useState(false)
  const [saving, setSaving] = useState(false)

  function download() {
    const blob = new Blob([content], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'postmortem.md'
    a.click()
    URL.revokeObjectURL(url)
  }

  async function handleSave() {
    setSaving(true)
    try {
      await savePostmortem(analysis.incidentId || null, title, content)
      setSaved(true)
    } catch (e) {
      console.error(e)
    } finally {
      setSaving(false)
    }
  }

  return (
    <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.8)', zIndex: 100, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 24 }}>
      <div style={{ background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 14, width: '100%', maxWidth: 760, maxHeight: '88vh', display: 'flex', flexDirection: 'column' }}>
        <div style={{ padding: '16px 20px', borderBottom: '1px solid var(--border)', background: 'var(--bg-secondary)', display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderRadius: '14px 14px 0 0' }}>
          <span style={{ fontFamily: 'var(--font-mono)', fontSize: 13, color: 'var(--text-secondary)', letterSpacing: '0.05em' }}>POSTMORTEM</span>
          <div style={{ display: 'flex', gap: 8 }}>
            <button onClick={() => navigator.clipboard.writeText(content)}
              style={{ display: 'flex', alignItems: 'center', gap: 5, padding: '6px 12px', background: 'var(--bg-primary)', border: '1px solid var(--border)', borderRadius: 6, color: 'var(--text-secondary)', fontSize: 12, fontFamily: 'var(--font-mono)', cursor: 'pointer' }}>
              <Copy size={12} />copy
            </button>
            <button onClick={download}
              style={{ display: 'flex', alignItems: 'center', gap: 5, padding: '6px 12px', background: 'var(--bg-primary)', border: '1px solid var(--border)', borderRadius: 6, color: 'var(--text-secondary)', fontSize: 12, fontFamily: 'var(--font-mono)', cursor: 'pointer' }}>
              <Download size={12} />.md
            </button>
            <button onClick={handleSave} disabled={saving || saved}
              style={{ display: 'flex', alignItems: 'center', gap: 5, padding: '6px 12px', background: saved ? 'var(--bg-primary)' : 'var(--accent)', border: 'none', borderRadius: 6, color: saved ? 'var(--green)' : '#000', fontSize: 12, fontFamily: 'var(--font-mono)', fontWeight: 700, cursor: saving || saved ? 'not-allowed' : 'pointer' }}>
              <Save size={12} />{saved ? 'saved' : saving ? 'saving...' : 'save'}
            </button>
            <button onClick={onClose} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-muted)', padding: '6px' }}><X size={16} /></button>
          </div>
        </div>
        <pre style={{ padding: '20px 24px', overflowY: 'auto', fontSize: 13, lineHeight: 1.8, color: 'var(--text-secondary)', fontFamily: 'var(--font-mono)', whiteSpace: 'pre-wrap', wordBreak: 'break-word', margin: 0 }}>
          {content}
        </pre>
      </div>
    </div>
  )
}
